version: '3.1'

services:
  slsdb:
    image: postgres:15.1
    container_name: slsdb
    environment:
      POSTGRES_DB: serverlessdb
      POSTGRES_USER: josue
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432